[package]
name = "blaze"
description = "A blazing fast Integrated Development Environment, meant to give power back to developers."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blaze_core.workspace = true
blaze_gui.workspace = true
pretty_env_logger.workspace = true

[workspace]
members = [ "core", "gui" ]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Redhawk18"]
license = "MIT"

[workspace.dependencies]
blaze_core = { path = "core" }
blaze_gui = { path = "gui" }

dark-light = "1.0.0"
iced = { version = "0.10.0", features = ["palette"] }
log = "0.4"
palette = "0.7.3"
pretty_env_logger = "0.5.0"
rfd = "0.12.0"
slotmap = "1.0.6"

[workspace.dependencies.iced_aw]
git = "https://github.com/Redhawk18/iced_aw.git"
rev = "132a84d"
default-features = false
features = ["icons", "menu", "tab_bar"]