[package]
name = "blaze"
description = "A blazing fast Integrated Development Environment, meant to give power back to developers."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blaze_gui.workspace = true
pretty_env_logger.workspace = true

[workspace]
members = [ "gui" ]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Redhawk18"]
license = "MIT"

[workspace.dependencies]
blaze_gui = { path = "gui" }

dark-light = "1.0"
iced = { version = "0.12", features = ["tokio"] }
iced_aw = { version = "0.8", features = ["icons", "menu","tab_bar"], default-features = false }
log = "0.4"
pattern_code = "0.1"
pretty_env_logger = "0.5"
rfd = { version = "0.13", features = ["xdg-portal", "tokio"], default-features = false}
slotmap = "1.0"
snafu = "0.8"
tokio = { version = "1", features = ["fs"] }

[patch.crates-io]
iced_aw = { git = 'https://github.com/iced-rs/iced_aw.git', rev = '99c12f1' }
