[package]
name = "code-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
iced_aw = { version = "0.5", default-features = false, features = ["menu", "split", "tab_bar", "tabs"] }
rfd = "0.11.4"
