[package]
name = "blaze"
version = "0.1.0"
edition = "2021"
description = "Hybrid UI integrated development environment"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blaze-core = { path = "core" }
blaze-gui = { path = "gui" }
blaze-tui = { path = "tui" }
clap = { version = "4.4.4", features = ["cargo"] }
log = "0.4.20"
pretty_env_logger = "0.5.0"
